In [4]:
import pillow_heif
from PIL import Image
import numpy as np
import tensorflow as tf

In [5]:
pillow_heif.register_heif_opener()

In [7]:
heic_image_path = 'C:/Users/DELL/OneDrive/Desktop/New folder/image2.heic'
image = Image.open(heic_image_path)

In [8]:
image = image.convert('RGB')
image.save('example_high_quality.jpg', 'JPEG', quality=100)

In [9]:
img = tf.keras.preprocessing.image.load_img(heic_image_path)

In [10]:
img_array = tf.keras.preprocessing.image.img_to_array(img)

In [11]:
print("Image array (matrix):\n", img_array)

Image array (matrix):
 [[[106. 136. 188.]
  [108. 138. 190.]
  [111. 141. 193.]
  ...
  [237. 226. 224.]
  [239. 228. 226.]
  [218. 207. 205.]]

 [[109. 139. 191.]
  [110. 140. 192.]
  [112. 142. 194.]
  ...
  [236. 225. 223.]
  [238. 227. 225.]
  [220. 209. 207.]]

 [[118. 143. 199.]
  [118. 143. 199.]
  [119. 144. 200.]
  ...
  [236. 225. 223.]
  [237. 226. 224.]
  [224. 213. 211.]]

 ...

 [[124. 143. 150.]
  [131. 150. 157.]
  [135. 139. 151.]
  ...
  [  8.  31.  37.]
  [ 16.  26.  35.]
  [ 23.  33.  42.]]

 [[137. 156. 163.]
  [140. 159. 166.]
  [144. 140. 155.]
  ...
  [ 16.  40.  50.]
  [ 10.  33.  41.]
  [ 14.  37.  45.]]

 [[129. 148. 155.]
  [119. 138. 145.]
  [110. 106. 121.]
  ...
  [ 20.  44.  54.]
  [ 14.  37.  45.]
  [ 16.  39.  47.]]]


In [12]:
New_image_path = 'C:/Users/DELL/OneDrive/Desktop/New folder/example_high_quality.jpg'

In [13]:
image = Image.open(New_image_path)

In [14]:
new_img = tf.keras.preprocessing.image.load_img(New_image_path)

In [15]:
new_img_array = tf.keras.preprocessing.image.img_to_array(new_img)

In [16]:
print("Image array (matrix):\n", new_img_array)

Image array (matrix):
 [[[106. 136. 188.]
  [108. 138. 190.]
  [110. 142. 193.]
  ...
  [237. 226. 224.]
  [239. 228. 226.]
  [218. 207. 205.]]

 [[111. 138. 191.]
  [110. 140. 192.]
  [112. 142. 194.]
  ...
  [236. 225. 223.]
  [238. 227. 225.]
  [220. 209. 207.]]

 [[118. 143. 199.]
  [117. 144. 199.]
  [118. 145. 200.]
  ...
  [236. 225. 223.]
  [237. 226. 224.]
  [224. 213. 211.]]

 ...

 [[124. 143. 150.]
  [134. 148. 157.]
  [133. 139. 151.]
  ...
  [ 10.  30.  37.]
  [ 13.  27.  36.]
  [ 21.  34.  42.]]

 [[136. 155. 162.]
  [143. 157. 166.]
  [140. 142. 155.]
  ...
  [ 16.  39.  47.]
  [ 11.  31.  40.]
  [ 17.  36.  43.]]

 [[129. 148. 155.]
  [123. 136. 145.]
  [106. 108. 121.]
  ...
  [ 20.  44.  54.]
  [ 13.  36.  44.]
  [ 16.  39.  47.]]]


In [17]:
difference_array = new_img_array - img_array

In [18]:
print("Image array (matrix):\n", difference_array)

Image array (matrix):
 [[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [-1.  1.  0.]
  ...
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 2. -1.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ...
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [-1.  1.  0.]
  [-1.  1.  0.]
  ...
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 ...

 [[ 0.  0.  0.]
  [ 3. -2.  0.]
  [-2.  0.  0.]
  ...
  [ 2. -1.  0.]
  [-3.  1.  1.]
  [-2.  1.  0.]]

 [[-1. -1. -1.]
  [ 3. -2.  0.]
  [-4.  2.  0.]
  ...
  [ 0. -1. -3.]
  [ 1. -2. -1.]
  [ 3. -1. -2.]]

 [[ 0.  0.  0.]
  [ 4. -2.  0.]
  [-4.  2.  0.]
  ...
  [ 0.  0.  0.]
  [-1. -1. -1.]
  [ 0.  0.  0.]]]


In [25]:
ori_magnitude = np.linalg.norm(img_array)
print(ori_magnitude)

628794.3


In [26]:
con_magnitude = np.linalg.norm(new_img_array)
print(con_magnitude)

628383.25


In [27]:
print(ori_magnitude - con_magnitude)

411.0625


-5.918127e-06


In [21]:
diff_magnitude = np.linalg.norm(difference_array)

In [22]:
print(diff_magnitude)

13742.124
